---

ansible_connection: local

nut_host: localhost
nut_max_retry: 3
nut_mode: netserver
nut_remove_shutdown_script: true

nut_ups_devices:
  - |
    [porter]
      driver = "usbhid-ups"
      port = "auto"
      vendorid = "0764"
      productid = "0501"
      product = "CP1500PFCLCD"
      serial = "000000000000"
      vendor = "CPS"
      bus = "001"
      desc = "CyberPower on porter"

nut_ups_monitors:
  - "MONITOR porter@192.168.10.125 1 {{ nut_user_master_name }} {{ nut_user_master_password }} master"

nut_exporter_enabled: true
nut_exporter_server: "192.168.10.125"
nut_driver_service_enabled: true
nut_ups_name: "porter"
